# -*- coding: utf-8 -*-
"""Task-3-lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fjMZf_B2xuPFtyLGva1quQgY1zsFg4PA
"""

import numpy as np
import cv2
import matplotlib.pyplot as plt

# FUNCION FILTRO PASA BAJAS FFT
def fft_lowpass_filter(img, radius=40):

    img_float = np.float32(img)

    F = np.fft.fft2(img_float)
    Fshift = np.fft.fftshift(F)

    rows, cols = img.shape
    crow, ccol = rows // 2 , cols // 2

    mask = np.zeros((rows, cols), np.uint8)

    for i in range(rows):
        for j in range(cols):
            if (i-crow)**2 + (j-ccol)**2 <= radius**2:
                mask[i,j] = 1

    F_filtered = Fshift * mask

    F_ishift = np.fft.ifftshift(F_filtered)
    img_back = np.fft.ifft2(F_ishift)
    img_back = np.abs(img_back)

    img_back = cv2.normalize(img_back, None, 0, 255, cv2.NORM_MINMAX)
    img_back = np.uint8(img_back)

    return img_back, mask, Fshift

# MORFOLOGIA LIMPIEZA
def clean_mask(binary):

    kernel = np.ones((5,5), np.uint8)

    opening = cv2.morphologyEx(binary, cv2.MORPH_OPEN, kernel, iterations=2)
    closing = cv2.morphologyEx(opening, cv2.MORPH_CLOSE, kernel, iterations=2)

    return closing


# PIPELINE COMPLETO
def process_image(path, radius):

    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    filtered, mask, Fshift = fft_lowpass_filter(img, radius)

    _, thresh = cv2.threshold(
        filtered, 0, 255,
        cv2.THRESH_BINARY + cv2.THRESH_OTSU
    )

    final = clean_mask(thresh)

    spectrum = 20*np.log(np.abs(Fshift)+1)

    plt.figure(figsize=(12,8))

    plt.subplot(231)
    plt.title("Original")
    plt.imshow(img, cmap='gray')

    plt.subplot(232)
    plt.title("FFT Spectrum")
    plt.imshow(spectrum, cmap='gray')

    plt.subplot(233)
    plt.title("IFFT Filtrado")
    plt.imshow(filtered, cmap='gray')

    plt.subplot(234)
    plt.title("Threshold")
    plt.imshow(thresh, cmap='gray')

    plt.subplot(235)
    plt.title("Final Mask")
    plt.imshow(final, cmap='gray')

    plt.tight_layout()
    plt.show()


# EJECUTAR CON TUS IMAGENES

# Ruido circular fuerte
process_image("fingerprint_noisy.png", radius=30)

# 2Ruido diagonal periódico
process_image("periodic_noise.jpg", radius=35)

# 3Textura + defecto (tipo tela)
process_image("textile_defect.jpg", radius=45)