# -*- coding: utf-8 -*-
"""Te damos la bienvenida a Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import math

def bytes_to_mib(num_bytes: float) -> float:
    """Convert bytes to MiB (2^20)."""
    return num_bytes / (2 ** 20)

def bits_per_second_to_gbps(bps: float) -> float:
    """Convert bits/s to Gbps (10^9)."""
    return bps / 1e9

def clamp(x: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, x))

def round_half_up(x: float) -> int:
    """Round half up (e.g., 125.5 -> 126)."""
    return int(math.floor(x + 0.5))

def rgb_to_hsv_normalized(r: int, g: int, b: int):
    """
    Convert RGB (0..255 ints) to HSV normalized:
    H in [0,1), S in [0,1], V in [0,1]
    """
    rf, gf, bf = r / 255.0, g / 255.0, b / 255.0
    cmax = max(rf, gf, bf)
    cmin = min(rf, gf, bf)
    delta = cmax - cmin

    if delta == 0:
        h = 0.0
    elif cmax == rf:
        h = ((gf - bf) / delta) % 6.0
        h /= 6.0
    elif cmax == gf:
        h = ((bf - rf) / delta) + 2.0
        h /= 6.0
    else:
        h = ((rf - gf) / delta) + 4.0
        h /= 6.0

    s = 0.0 if cmax == 0 else (delta / cmax)

    v = cmax

    h = h % 1.0
    s = clamp(s, 0.0, 1.0)
    v = clamp(v, 0.0, 1.0)
    return (h, s, v)


def task1_autonomous_cameras(
    width=3840,
    height=2160,
    bits_per_pixel=12,
    fps=60,
    num_cameras=8,
    buffer_gib=16
):
    pixels_per_frame = width * height
    bytes_per_pixel = bits_per_pixel / 8.0
    bytes_per_frame = pixels_per_frame * bytes_per_pixel

    frame_mib = bytes_to_mib(bytes_per_frame)

    bps_per_camera = bytes_per_frame * 8.0 * fps
    gbps_per_camera = bits_per_second_to_gbps(bps_per_camera)

    total_bps = bps_per_camera * num_cameras
    total_gbps = bits_per_second_to_gbps(total_bps)

    bytes_per_sec_total = bytes_per_frame * fps * num_cameras

    buffer_bytes = buffer_gib * (2 ** 30)

    seconds_history = buffer_bytes / bytes_per_sec_total

    return {
        "pixels_per_frame": pixels_per_frame,
        "bytes_per_pixel": bytes_per_pixel,
        "bytes_per_frame": bytes_per_frame,
        "frame_mib": frame_mib,
        "gbps_per_camera": gbps_per_camera,
        "total_gbps": total_gbps,
        "bytes_per_sec_total": bytes_per_sec_total,
        "total_mib_per_sec": bytes_to_mib(bytes_per_sec_total),
        "seconds_history": seconds_history,
    }


def task2_image_enhancement(
    I_in=50,
    gamma=0.5,
    alpha=1.2,
    beta=-10
):
    f = I_in / 255.0
    f1 = f ** gamma
    beta_n = beta / 255.0
    f2 = alpha * f1 + beta_n

    clipped = not (0.0 <= f2 <= 1.0)
    f2c = clamp(f2, 0.0, 1.0)

    I_out_float = round_half_up(f2c * 255.0)

    I_gamma_wrong = int((I_in ** gamma))

    I_linear_wrong = int(I_gamma_wrong * alpha)
    I_linear_wrong = I_linear_wrong + beta
    I_linear_wrong = int(clamp(I_linear_wrong, 0, 255))

    error = abs(I_linear_wrong - I_out_float)

    return {
        "f": f,
        "f1": f1,
        "beta_n": beta_n,
        "f2": f2,
        "clipped": clipped,
        "f2_clamped": f2c,
        "I_out_float": I_out_float,
        "I_wrong_uint8": I_linear_wrong,
        "abs_error": error,
        "I_gamma_wrong": I_gamma_wrong,
    }


def task3_robot_classifier(
    R_rgb=(255, 0, 0),
    S_rgb=(50, 0, 0)
):
    r1, g1, b1 = R_rgb
    r2, g2, b2 = S_rgb

    dist_rgb = math.sqrt((r1 - r2) ** 2 + (g1 - g2) ** 2 + (b1 - b2) ** 2)

    R_hsv = rgb_to_hsv_normalized(r1, g1, b1)
    S_hsv = rgb_to_hsv_normalized(r2, g2, b2)

    dH = abs(R_hsv[0] - S_hsv[0])
    dS = abs(R_hsv[1] - S_hsv[1])
    dV = abs(R_hsv[2] - S_hsv[2])

    return {
        "dist_rgb": dist_rgb,
        "R_hsv": R_hsv,
        "S_hsv": S_hsv,
        "dH": dH,
        "dS": dS,
        "dV": dV,
    }
def main():
    print("=== TASK 1: Conducción autónoma (cámaras raw) ===")
    t1 = task1_autonomous_cameras()
    print(f"Pixeles por frame: {t1['pixels_per_frame']:,}")
    print(f"Bytes por píxel: {t1['bytes_per_pixel']:.4f} B")
    print(f"Bytes por frame: {t1['bytes_per_frame']:,} B")
    print(f"Tamaño frame: {t1['frame_mib']:.2f} MiB (2^20 bytes)")
    print(f"Ancho de banda por cámara: {t1['gbps_per_camera']:.3f} Gbps")
    print(f"Ancho de banda total (8 cámaras): {t1['total_gbps']:.3f} Gbps")
    print(f"Throughput total: {t1['total_mib_per_sec']:.1f} MiB/s")
    print(f"Historia en buffer (16 GiB): {t1['seconds_history']:.2f} s")

    print("\nComentario 5G:")
    print("- Si necesitás ~48 Gbps de subida, no es viable en 5G real.")
    print("- Solución típica: compresión + preprocesamiento local (edge) + subir features/eventos.\n")

    print("=== TASK 2: Mejora de imagen (float vs uint8) ===")
    t2 = task2_image_enhancement()
    print(f"I_in = 50")
    print(f"Normalizado f = {t2['f']:.8f}")
    print(f"Gamma (γ=0.5): f1 = {t2['f1']:.6f}")
    print(f"Beta normalizado (β=-10): beta_n = {t2['beta_n']:.8f}")
    print(f"Ajuste lineal: f2 = {t2['f2']:.6f}")
    print(f"Clipping?: {'Sí' if t2['clipped'] else 'No'}")
    print(f"f2 clamped = {t2['f2_clamped']:.6f}")
    print(f"I_out (float correcto) = {t2['I_out_float']}")

    print("\nSimulación incorrecta en uint8 (truncando en pasos):")
    print(f"Paso gamma errado (int): I_gamma_wrong = {t2['I_gamma_wrong']}")
    print(f"I_out wrong uint8 = {t2['I_wrong_uint8']}")
    print(f"Error absoluto = {t2['abs_error']}")

    print("\n=== TASK 3: Robot clasificador (RGB vs HSV) ===")
    t3 = task3_robot_classifier()
    print(f"Distancia RGB (euclidiana) = {t3['dist_rgb']:.0f}")
    Rh, Rs, Rv = t3["R_hsv"]
    Sh, Ss, Sv = t3["S_hsv"]
    print(f"R HSV = (H={Rh:.4f}, S={Rs:.4f}, V={Rv:.4f})")
    print(f"S HSV = (H={Sh:.4f}, S={Ss:.4f}, V={Sv:.4f})")
    print(f"Diferencias |ΔH|={t3['dH']:.4f}, |ΔS|={t3['dS']:.4f}, |ΔV|={t3['dV']:.4f}")


if __name__ == "__main__":
    main()